# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  ## Sources (not required for vagrantup.com)
  #config.vm.box_url = "http://files.vagrantup.com/customBox.box"
  #config.vm.box_url = "file:///C:/path/to/vagrant/customBox.box"
  #config.vm.box_url = "file:///opt/vagrant/boxes/customBox.box"
  
  
  
  
  
  ## Box (required) - Template
  config.vm.box = "vavyskov/symfony"
  
  ## Enable when do not use "Template"
#  config.vm.box = "debian/contrib-stretch64"
#  config.vm.provision :shell, path: "config/symfony.sh"  
#  config.vm.provision :shell, path: "config/symfony-dev.sh"





  ## Hostname
  config.vm.hostname = "devel.example.com"

  ## Guest hostname with prefix from the host computer
  #config.vm.hostname = "#{`hostname`[0..-2]}".sub(/\..*$/,'')+".example.com"

  ## Network
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"





  ## Share folder  
  config.vm.synced_folder "../workspace", "/var/nfs",
    id:"default",
    type:"nfs", 
    mount_options:['rw','vers=3','tcp'],
    linux__nfs_options:['rw', 'no_subtree_check', 'all_squash', 'async'],
    bsd__nfs_options:['rw', 'no_subtree_check', 'all_squash', 'async']

  config.nfs.map_uid = Process.uid
  config.nfs.map_gid = Process.gid
  
  config.bindfs.bind_folder "/var/nfs", "/home/vagrant/www"
  
  #config.bindfs.bind_folder "/vagrant-after-provision", "another/guest/mount/point", after: :provision





  ## Backup database
  config.trigger.before [:halt, :suspend, :destroy, :save] do |backup|
    backup.info = "The database has been BACKUPED!"
    #backup.run_remote = {inline: "PGUSER=postgres PGPASSWORD=postgres pg_dumpall | gzip > /vagrant/database/postgres.sql.gz"}
    backup.run_remote = {path: "./vagrant/config/db-backup.sh `hostname`"}
  end
  
  ## Restore database
  config.trigger.after [:up, :resume, :reload, :restore] do |restore|
    restore.info = "The database has been RESTORED!"
    #restore.run_remote = {inline: "gunzip < /vagrant/database/postgres.sql.gz | PGUSER=postgres PGPASSWORD=postgres psql postgres"}
    restore.run_remote = {path: "./vagrant/config/db-restore.sh `hostname`"}
  end
  
  ## WinNFSd
  #config.trigger.after :destroy do |trigger|
  #  trigger.info = "Destroy winnfsd process"
  #  trigger.run = "Taskkill /IM winnfsd.exe /F"
  #end





  ## VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "symfony"
    vb.cpus = 1
    vb.memory = 2048
    ## HDD cache off !!!
    vb.customize [
      "storagectl", :id, 
      "--name", "SATA Controller", 
      "--hostiocache", "off"
    ]
    ## Fix slow DNS lookups
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

end
